### ISSUE TITLE
Role Selection Boxes Can't Be Filled In

### ISSUE THREAD

**Issue by discuit** [mcglincy/downwego-foundry-vtt#1]
Hi, I'm just wondering if this is happening to others, when I click on a role ability box, it records it in the Lvl count but does not fill in the box. Thanks!

**Comment by mcglincy** [comment]
Thanks for the bug report! 

This is what I see on my local Foundry server (using macos Chrome): 

![Screenshot 2023-05-12 at 7 55 13 AM](https://github.com/mcglincy/downwego-foundry-vtt/assets/189172/9d9ac951-d3f9-4a1e-a650-43ab987e7614)

Seems like something may be goofed in the CSS styling or display somehow. From our discord chat: you're using Win 10/11, Chrome, and this is happening even with all other modules disabled.

**Comment by mcglincy** [comment]
Followup info: this issue seems to be specific to the Foundry console browser / electron wrapper. Using a separate chrome window on the same machine seems to look fine.

**Comment by mcglincy** [comment]
Fixed.
